// This TypeScript modules definition file is generated by vaadin-maven-plugin.
// You can not directly import your different static files into TypeScript,
// This is needed for TypeScript compiler to declare and export as a TypeScript module.
// It is recommended to commit this file to the VCS.
// You might want to change the configurations to fit your preferences
declare module '*.css?inline' {
  import type { CSSResultGroup } from 'lit';
  const content: CSSResultGroup;
  export default content;
}

// Allow any CSS Custom Properties
declare module 'csstype' {
  interface Properties {
    [index: `--${string}`]: any;
  }
}

// Make this file a module (enables declare global)
export {};

// ============================================================
// LiveKit window function declarations
// These functions are defined in livekit-client.js and called
// from LiveRoomView.java via executeJs()
// ============================================================

interface LkConfig {
  roomId: string;
  role: string;
  displayName: string;
  previewStageId: string;
  liveStageId: string;
}

interface LkTrackNodes {
  get(key: string): HTMLElement | undefined;
  set(key: string, value: HTMLElement): void;
  delete(key: string): void;
  clear(): void;
}

interface LkState {
  room: import('livekit-client').Room | null;
  config: LkConfig | null;
  previewTracks: import('livekit-client').LocalTrack[];
  trackNodes: LkTrackNodes;
  joined: boolean;
  previewSummary: string;
}

declare global {
  interface Window {
    lk: LkState;
    initLiveRoom(roomId: string, role: string, displayName: string, previewStageId: string, liveStageId: string): void;
    startPreview(): Promise<void>;
    joinLiveRoom(): Promise<void>;
    startScreenShare(): Promise<void>;
    muteAllByTeacher(roomId: string): Promise<{ mutedTracks?: number; message?: string }>;
    leaveLiveRoom(clearStudentSession: boolean): Promise<void>;
  }
}
