spring.application.name=class-room
server.port=8091
spring.datasource.url=jdbc:postgresql://localhost:5432/classroom
spring.datasource.username=mhcybroot
spring.datasource.password=MhR@2025
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# s
vaadin.launch-browser=false

app.content.about-title=About Our Classroom
app.content.about-body=We provide mobile-first virtual classes for teachers and students.
app.content.contact-title=Contact Us
app.content.contact-body=Reach out for support and onboarding.
app.content.support-email=support@classroom.local
app.content.support-phone=+8801700000000



app.bootstrap-admin.email=teacher@example.com
app.bootstrap-admin.password=ChangeMe123!
app.bootstrap-admin.full-name=Default Teacher

livekit.url=ws://localhost:7880
livekit.api-key=APID7EKu4ZbrhJJ
livekit.api-secret=EV4IxoTrPsf8hNZwsOnA9kqoiBA8T2yUWOO6lfUYNDG
